#!/usr/bin/perl
#-------------------------------------------------+
#    [APM] This script was generated by amp.pl    |
#    [APM] Created time: 2016-04-16 11:31:25      |
#-------------------------------------------------+
# name: parse_sbv.pl
# func: 
# version:: 0.1

use strict;
use warnings;

my $file = shift @ARGV;
my $chr = shift @ARGV;
my $start = shift @ARGV;

my %hash = ();

open IN,$file or die $!;

while(<IN>)
{
	chomp;
	my ($chr1,$len1,$sta1,$end1,$chr2,$len2,$sta2,$end2,$identity) = split /\t/;
	
	if ($hash{$sta1}{$sta2})
	{
		next;
	}
	
	$hash{$sta1}{$sta2} = 1;
	$hash{$sta2}{$sta1} = 1;
	
	$sta1 += $start-1;
	$end1 += $start-1;
	$sta2 += $start-1;
	$end2 += $start-1;

	print "$chr\t$sta1\t$end1\t$chr\t$sta2\t$end2\n";

}

close IN;
