package SBV::IMAGE::GOBAR;
#-------------------------------------------------+
#    [APM] This moudle was generated by amp.pl    |
#    [APM] Created time: 2016-09-14 17:54:09      |
#-------------------------------------------------+
=pod

=head1 Name

SBV::IMAGE::GOBAR

=head1 Synopsis

This module is not meant to be used directly

=head1 Feedback

Author: Peng Ai
Email:  aipeng0520@163.com

=head1 Version

Version history

=head2 v1.0

Date: 2016-09-14 17:54:09

=cut


use strict;
use warnings;
require Exporter;
our @ISA = qw(Exporter);

use FindBin;
use lib "$FindBin::RealBin";
use lib "$FindBin::RealBin/lib";
use lib "$FindBin::RealBin/../";
use lib "$FindBin::RealBin/../lib";

sub new 
{
	my ($class,$file,$conf) = @_;

	my $gobar = {};
	_load_file($gobarv,$file,$conf);
	$gobarv->{conf} = $conf;
	bless $gobarv , $class;
	return $gobarv
}

sub plot 
{
	
}

sub _load_file
{
	
}
